# Generated by Django 3.0.6 on 2021-05-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lon',
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
