# Generated by Django 3.0.6 on 2021-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210523_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.Location'),
        ),
    ]
