# Generated by Django 3.1.5 on 2021-03-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'CENSUS_PERSONS',
                'managed': False,
            },
        ),
    ]
