# Generated by Django 3.1.5 on 2021-03-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='PERSON_OR',
        ),
    ]
