# Generated by Django 3.1.5 on 2021-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamal_oracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KntDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'KNT_DETAIL',
                'managed': False,
            },
        ),
    ]
